In [1]:
import numpy as np 
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

In [2]:
df = pd.read_csv("train.csv", delimiter=",")
df[0:5]

Id  Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0   1       2596      51      3                               258   
1   2       2590      56      2                               212   
2   3       2804     139      9                               268   
3   4       2785     155     18                               242   
4   5       2595      45      2                               153   

   Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                               0                              510   
1                              -6                              390   
2                              65                             3180   
3                             118                             3090   
4                              -1                              391   

   Hillshade_9am  Hillshade_Noon  Hillshade_3pm     ...      Soil_Type32  \
0            221             232            148     ...                0   
1            220             235            151     ...                0   
2            234             238            135     ...                0   
3            238             238            122     ...                0   
4            220             234            150     ...                0   

   Soil_Type33  Soil_Type34  Soil_Type35  Soil_Type36  Soil_Type37  \
0            0            0            0            0            0   
1            0            0            0            0            0   
2            0            0            0            0            0   
3            0            0            0            0            0   
4            0            0            0            0            0   

   Soil_Type38  Soil_Type39  Soil_Type40  Cover_Type  
0            0            0            0           5  
1            0            0            0           5  
2            0            0            0           2  
3            0            0            0           2  
4            0            0            0           5  

[5 rows x 56 columns]

In [3]:
X = df[['Id', 'Elevation', 'Aspect', 'Horizontal_Distance_To_Hydrology', 'Slope']].values
X[0:5]

array([[   1, 2596,   51,  258,    3],
       [   2, 2590,   56,  212,    2],
       [   3, 2804,  139,  268,    9],
       [   4, 2785,  155,  242,   18],
       [   5, 2595,   45,  153,    2]], dtype=int64)

In [4]:
import numpy as np
import pandas as pd
from sklearn.cross_validation import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn import tree

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [5]:
df.head()

Id  Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0   1       2596      51      3                               258   
1   2       2590      56      2                               212   
2   3       2804     139      9                               268   
3   4       2785     155     18                               242   
4   5       2595      45      2                               153   

   Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                               0                              510   
1                              -6                              390   
2                              65                             3180   
3                             118                             3090   
4                              -1                              391   

   Hillshade_9am  Hillshade_Noon  Hillshade_3pm     ...      Soil_Type32  \
0            221             232            148     ...                0   
1            220             235            151     ...                0   
2            234             238            135     ...                0   
3            238             238            122     ...                0   
4            220             234            150     ...                0   

   Soil_Type33  Soil_Type34  Soil_Type35  Soil_Type36  Soil_Type37  \
0            0            0            0            0            0   
1            0            0            0            0            0   
2            0            0            0            0            0   
3            0            0            0            0            0   
4            0            0            0            0            0   

   Soil_Type38  Soil_Type39  Soil_Type40  Cover_Type  
0            0            0            0           5  
1            0            0            0           5  
2            0            0            0           2  
3            0            0            0           2  
4            0            0            0           5  

[5 rows x 56 columns]

In [6]:
df.Cover_Type.value_counts().sort_index()

1    2160
2    2160
3    2160
4    2160
5    2160
6    2160
7    2160
Name: Cover_Type, dtype: int64

In [7]:
df.columns

Index(['Id', 'Elevation', 'Aspect', 'Slope',
       'Horizontal_Distance_To_Hydrology', 'Vertical_Distance_To_Hydrology',
       'Horizontal_Distance_To_Roadways', 'Hillshade_9am', 'Hillshade_Noon',
       'Hillshade_3pm', 'Horizontal_Distance_To_Fire_Points',
       'Wilderness_Area1', 'Wilderness_Area2', 'Wilderness_Area3',
       'Wilderness_Area4', 'Soil_Type1', 'Soil_Type2', 'Soil_Type3',
       'Soil_Type4', 'Soil_Type5', 'Soil_Type6', 'Soil_Type7', 'Soil_Type8',
       'Soil_Type9', 'Soil_Type10', 'Soil_Type11', 'Soil_Type12',
       'Soil_Type13', 'Soil_Type14', 'Soil_Type15', 'Soil_Type16',
       'Soil_Type17', 'Soil_Type18', 'Soil_Type19', 'Soil_Type20',
       'Soil_Type21', 'Soil_Type22', 'Soil_Type23', 'Soil_Type24',
       'Soil_Type25', 'Soil_Type26', 'Soil_Type27', 'Soil_Type28',
       'Soil_Type29', 'Soil_Type30', 'Soil_Type31', 'Soil_Type32',
       'Soil_Type33', 'Soil_Type34', 'Soil_Type35', 'Soil_Type36',
       'Soil_Type37', 'Soil_Type38', 'Soil_Type39', 'Soil_

In [8]:
#df1=df.pop("Cover_Type")
#df1

In [9]:
df.iloc[:,1:55]

Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0           2596      51      3                               258   
1           2590      56      2                               212   
2           2804     139      9                               268   
3           2785     155     18                               242   
4           2595      45      2                               153   
5           2579     132      6                               300   
6           2606      45      7                               270   
7           2605      49      4                               234   
8           2617      45      9                               240   
9           2612      59     10                               247   
10          2612     201      4                               180   
11          2886     151     11                               371   
12          2742     134     22                               150   
13          2609     214      7                               150   
14          2503     157      4                                67   
15          2495      51      7                                42   
16          2610     259      1                               120   
17          2517      72      7                                85   
18          2504       0      4                                95   
19          2503      38      5                                85   
20          2501      71      9                                60   
21          2880     209     17                               216   
22          2768     114     23                               192   
23          2511      54      8                               124   
24          2507      22      9                               120   
25          2492     135      6                                 0   
26          2489     163     10                                30   
27          2962     148     16                               323   
28          2811     135      1                               212   
29          2739     117     24                               127   
...          ...     ...    ...                               ...   
15090       2417     194     21                                42   
15091       2614       4     18                               150   
15092       2529      43     33                               319   
15093       2404     194      4                                 0   
15094       2426      14     30                                67   
15095       2410      19     22                                30   
15096       2478      38     32                               192   
15097       2653     343     10                               192   
15098       2661       8      7                               234   
15099       2514      34     33                               256   
15100       2519     341     22                               467   
15101       2496      32     23                               150   
15102       2576      43     21                               283   
15103       2563      23     31                                85   
15104       2566     259     10                               421   
15105       2480      10     21                               150   
15106       2656      66     11                               524   
15107       2600     293     14                               330   
15108       2593      38     21                               120   
15109       2600      57     19                                 0   
15110       2508      33     26                                67   
15111       2610      59     17                                60   
15112       2600      38     25                               124   
15113       2688     104     15                               443   
15114       2670     108     12                               624   
15115       2607     243     23                               258   
15116

In [10]:
df.iloc[:,-1]

0        5
1        5
2        2
3        2
4        5
5        2
6        5
7        5
8        5
9        5
10       5
11       2
12       2
13       5
14       5
15       5
16       5
17       5
18       5
19       5
20       5
21       2
22       5
23       5
24       5
25       5
26       5
27       2
28       2
29       5
        ..
15090    3
15091    3
15092    3
15093    6
15094    6
15095    6
15096    6
15097    3
15098    3
15099    6
15100    3
15101    6
15102    3
15103    6
15104    3
15105    6
15106    3
15107    3
15108    3
15109    6
15110    6
15111    6
15112    6
15113    3
15114    3
15115    3
15116    3
15117    3
15118    3
15119    3
Name: Cover_Type, Length: 15120, dtype: int64

In [11]:
X = df.values[:, 1:55]
y = df.values[:,-1]

In [12]:
X

array([[2596,   51,    3, ...,    0,    0,    0],
       [2590,   56,    2, ...,    0,    0,    0],
       [2804,  139,    9, ...,    0,    0,    0],
       ...,
       [2492,  134,   25, ...,    0,    0,    0],
       [2487,  167,   28, ...,    0,    0,    0],
       [2475,  197,   34, ...,    0,    0,    0]], dtype=int64)

In [13]:
X.shape

(15120, 54)

In [14]:
y

array([5, 5, 2, ..., 3, 3, 3], dtype=int64)

In [15]:
y.shape

(15120,)

In [16]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=3)

In [17]:
print(X_test)
X_test.shape

[[3334    9    6 ...    0    0    0]
 [2811  135    1 ...    0    0    0]
 [3675   44   18 ...    0    0    1]
 ...
 [3307  345   15 ...    0    1    0]
 [2491  215   34 ...    0    0    0]
 [2825   92   25 ...    0    0    0]]


(3024, 54)

In [18]:
y_train

array([3, 2, 4, ..., 2, 1, 6], dtype=int64)

In [19]:
y_train.shape

(12096,)

In [20]:
y_test

array([7, 2, 1, ..., 7, 3, 5], dtype=int64)

In [21]:
y_test.shape

(3024,)

In [22]:
X_train

array([[2083,   90,   30, ...,    0,    0,    0],
       [2344,   45,   17, ...,    0,    0,    0],
       [3237,  120,   36, ...,    0,    1,    0],
       ...,
       [3057,   75,   11, ...,    0,    0,    0],
       [3252,   37,   18, ...,    1,    0,    0],
       [2425,    0,   11, ...,    0,    0,    0]], dtype=int64)

In [22]:
cover_gini = DecisionTreeClassifier(criterion = "gini", random_state = 100,
                               max_depth=3, min_samples_leaf=5)
cover_gini.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [23]:
cover_entropy = DecisionTreeClassifier(criterion = "entropy", random_state = 100,
 max_depth=3, min_samples_leaf=5)
cover_entropy.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [24]:
cover_gini.predict(X_train)

array([5, 5, 4, ..., 1, 7, 6], dtype=int64)

In [25]:
cover_gini.predict(X_test)

array([7, 5, 7, ..., 7, 3, 5], dtype=int64)

In [26]:
y_pred = cover_gini.predict(X_train)
y_pred

array([5, 5, 4, ..., 1, 7, 6], dtype=int64)

In [27]:
y_pred.shape

(12096,)

In [28]:
y_p1=pd.DataFrame(y_pred)
y_p1.columns=["c"]
y_p1.head()

c
0  5
1  5
2  4
3  6
4  4

In [29]:
y_p1.c.value_counts().sort_index()

1    1793
3    1325
4    1985
5    2851
6    1945
7    2197
Name: c, dtype: int64

In [30]:
y_pred_en=cover_entropy.predict(X_test)
y_pred_en

array([7, 5, 7, ..., 7, 6, 5], dtype=int64)

In [35]:
y_p1=pd.DataFrame(y_pred_en)
y_p1.columns=["c"]
y_p1.head()

c
0  7
1  5
2  7
3  2
4  7

In [36]:
y_p1.c.value_counts().sort_index()

1    371
2    276
3    242
4    571
5    569
6    482
7    513
Name: c, dtype: int64

In [37]:
print ("Accuracy is ", accuracy_score(y_train,y_pred)*100)

Accuracy is  60.58201058201058


In [38]:
print ("Accuracy is ", accuracy_score(y_test,y_pred_en)*100)

Accuracy is  59.5568783068783


In [41]:
cv=pd.read_csv("test.csv")
cv.head()

Id  Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0  15121       2680     354     14                                 0   
1  15122       2683       0     13                                 0   
2  15123       2713      16     15                                 0   
3  15124       2709      24     17                                 0   
4  15125       2706      29     19                                 0   

   Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                               0                             2684   
1                               0                             2654   
2                               0                             2980   
3                               0                             2950   
4                               0                             2920   

   Hillshade_9am  Hillshade_Noon  Hillshade_3pm     ...       Soil_Type31  \
0            196             214            156     ...                 0   
1            201             216            152     ...                 0   
2            206             208            137     ...                 0   
3            208             201            125     ...                 0   
4            210             195            115     ...                 0   

   Soil_Type32  Soil_Type33  Soil_Type34  Soil_Type35  Soil_Type36  \
0            0            0            0            0            0   
1            0            0            0            0            0   
2            0            0            0            0            0   
3            0            0            0            0            0   
4            0            0            0            0            0   

   Soil_Type37  Soil_Type38  Soil_Type39  Soil_Type40  
0            0            0            0            0  
1            0            0            0            0  
2            0            0            0            0  
3            0            0            0            0  
4            0            0            0            0  

[5 rows x 55 columns]

In [42]:
cv.shape

(565892, 55)

In [43]:
import numpy as np
import pandas as pd
from sklearn.cross_validation import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn import tree

In [44]:
y_pred

array([5, 5, 4, ..., 1, 7, 6], dtype=int64)

In [45]:
y_pred.shape

(12096,)

In [46]:
c=np.zeros((565892,1))
print(c)
c.shape

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


(565892, 1)

In [104]:
X1 = cv.values[:, 1:54]
y1 = cv.values[:,-1]

In [105]:
X1

array([[2680,  354,   14, ...,    0,    0,    0],
       [2683,    0,   13, ...,    0,    0,    0],
       [2713,   16,   15, ...,    0,    0,    0],
       ...,
       [2386,  159,   17, ...,    0,    0,    0],
       [2384,  170,   15, ...,    0,    0,    0],
       [2383,  165,   13, ...,    0,    0,    0]], dtype=int64)

In [106]:
y1

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [109]:
y_test

array([7, 2, 1, ..., 2, 6, 6], dtype=int64)

In [60]:
X_test

array([[2919,   86,    8, ...,    0,    0,    0],
       [3137,  239,   29, ...,    0,    0,    0],
       [3075,  238,   12, ...,    0,    0,    0],
       ...,
       [2808,   11,   16, ...,    0,    0,    0],
       [2828,  301,   26, ...,    0,    0,    0],
       [2975,  243,   11, ...,    0,    0,    0]], dtype=int64)

In [61]:
y_train

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [111]:
cover_gini = DecisionTreeClassifier(criterion = "gini", random_state = 100,
                               max_depth=3, min_samples_leaf=5)
cover_gini.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [112]:
cover_entropy = DecisionTreeClassifier(criterion = "entropy", random_state = 100,
 max_depth=3, min_samples_leaf=5)
cover_entropy.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [113]:
cover_gini.predict(X_train)

array([4, 4, 7, ..., 1, 7, 6], dtype=int64)

In [114]:
y_pred=cover_gini.predict(X_test)
y_pred

array([7, 5, 7, ..., 1, 3, 3], dtype=int64)

In [115]:
y_p1=pd.DataFrame(y_pred)
y_p1

0
0     7
1     5
2     7
3     1
4     7
5     3
6     7
7     1
8     3
9     3
10    1
11    1
12    7
13    7
14    4
15    1
16    5
17    3
18    1
19    1
20    1
21    4
22    1
23    4
24    5
25    3
26    1
27    5
28    1
29    7
...  ..
4506  3
4507  1
4508  4
4509  5
4510  3
4511  1
4512  1
4513  3
4514  4
4515  5
4516  1
4517  5
4518  3
4519  1
4520  5
4521  5
4522  1
4523  7
4524  7
4525  5
4526  7
4527  3
4528  1
4529  7
4530  5
4531  4
4532  3
4533  1
4534  3
4535  3

[4536 rows x 1 columns]

In [116]:
y_pred_en=cover_entropy.predict(X_test)
y_pred_en

array([7, 5, 7, ..., 1, 3, 3], dtype=int64)

In [117]:
print ("Accuracy is ", accuracy_score(y_test,y_pred)*100)

Accuracy is  59.63403880070547


In [118]:
print ("Accuracy is ", accuracy_score(y_test,y_pred_en)*100)

Accuracy is  59.70017636684304
